#连接数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apsfc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    driverClassName: com.mysql.jdbc.Driver
  #访问静态页面
  mvc:
    view:
      prefix: /public/
      suffix: .jsp
  web:
    resources:
      static-locations: classpath:/META-INF/resources

  servlet:
    multipart:
      # \u5F00\u542F\u6587\u4EF6\u4E0A\u4F20
      enabled: true
      # \u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-file-size: 10MB
      # \u6240\u6709\u6587\u4EF6\u5927\u5C0F
      max-request-size: 100MB